version: '3'
services:
  ev_db:
    container_name: ev-dim
    image: postgres:alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    mem_limit: 500M
